apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aetherium-manifest.fullname" . }}-governor-schema
  labels:
    {{- include "aetherium-manifest.labels" . | nindent 4 }}
data:
  particle-control.schema.json: |
{{ .Files.Get "files/governor/particle-control.schema.json" | indent 4 }}
